have_fun: true
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: true
    summary: true
    code_review: true
ignore_patterns:
  - "*.min.js"
  - "*.min.css"
  - "node_modules/**"
  - "build/**"
  - "dist/**"
  - "*.log"
  - "*.tmp"
  - "vendor/**"
  - "__pycache__/**"
  - "*.pyc"
  - ".env*"
  - "*.lock"
  - "coverage/**"
  - "docs/_build/**"
  - "*mock*"
  - "*migration*"
  - "*test*"
  - "*tests*"