$schema: "http://json-schema.org/draft-07/schema#"
title: AutoSyncFork
description: Configuration for Gemini Code Assist on Auto Sync Fork repository. All fields are optional and have default values.
type: object
properties:
  have_fun: true
  ignore_patterns:
    - "*.min.js"
    - "*.min.css"
    - "node_modules/**"
    - "build/**"
    - "dist/**"
    - "*.log"
    - "*.tmp"
    - "vendor/**"
    - "__pycache__/**"
    - "*.pyc"
    - ".env*"
    - "*.lock"
    - "coverage/**"
    - "docs/_build/**"
  code_review:
    disable: false
    comment_severity_threshold: MEDIUM
    max_review_comments: -1
    pull_request_opened:
      help: true
      summary: true
      code_review: true
