name: Auto Sync Forks

on:
  schedule:
    - cron: '0 0 * * 0'
    # Cronjob default is weekly on Sunday at 00:00, change suitable for you
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      YOUR_USERNAME_OR_ORGANIZATION_NAME: ${{ vars.YOUR_USERNAME_OR_ORGANIZATION_NAME || 'paulpham157' }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install
        
      - name: Run sync script
        run: npm start